FROM registry.fedoraproject.org/fedora:35 as baseimg
USER 0
WORKDIR /

RUN yum install -y git vim 
RUN chmod 777 /tmp

ADD donkeycar /root/donkeycar

ADD donkeycar.arm64.sh /tmp
RUN bash /tmp/donkeycar.arm64.sh

ADD mycar.arm64.sh /tmp
RUN bash /tmp/mycar.arm64.sh

# For RPI Only
ADD pi-userland.sh /tmp
RUN bash /tmp/pi-userland.sh
